import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/site-config";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: [
          "/",
          "/spotify-canvas-maker",
          "/spotify-canvas-handbook",
          "/ultimate-guide-ai-loop-video",
          "/pricing",
          "/gallery",
          "/gallery/*",
          "/blog/",
          "/blog/*",
          "/legal/",
          "/legal/*",
          // Phase 6 SEO landing pages
          "/loop-video-generator",
          "/ai-loop-video",
          "/seamless-loop-video",
          "/text-to-video",
          "/photo-to-video",
          "/website-background-video",
          "/ai-video-generator",
          "/free-loop-video-maker",
          "/loop-video-for-social-media",
          "/loop-video-for-websites",
          "/loop-video-for-instagram",
          "/loop-video-for-tiktok",
          "/ai-video-background-generator",
          "/short-loop-video-maker",
          // Phase 7 — 21 new SEO pages (2026-06-05)
          "/ai-loop-video-applications",
          "/ai-loop-video-tools-compared",
          "/ai-video-presentation-background",
          "/album-art-motion-design",
          "/how-ai-loop-video-works",
          "/loop-video-ad-creative",
          "/loop-video-digital-art-nft",
          "/loop-video-ecommerce-product",
          "/loop-video-for-music-album-release",
          "/loop-video-music-visualizer",
          "/loop-video-vs-traditional",
          "/loop-video-wedding-event",
          "/music-festival-loop-video",
          "/music-visual-content-guide",
          "/online-course-loop-background",
          "/seamless-loop-technical-guide",
          "/social-media-loop-trends-2026",
          "/spotify-canvas-vs-lyric-video",
          "/twitch-stream-loop-overlay",
        ],
        disallow: [
          "/api/",
          "/api/*",
          "/auth/",
          "/auth/*",
          "/checkout/",
          "/checkout/*",
          "/portal/",
          "/portal/*",
          "/profile/",
          "/profile/*",
          "/dashboard/",
          "/dashboard/*",
          "/account/",
          "/account/*",
          "/result/",
          "/result/*",
          "/_next/",
          "/cgi-bin/",
          "/*?ref=",
          "/*?utm_",
          "/*?token=",
        ],
      },
      // AI training crawlers — deny all
      { userAgent: "GPTBot", disallow: "/" },
      { userAgent: "CCBot", disallow: "/" },
      { userAgent: "ClaudeBot", disallow: "/" },
      { userAgent: "anthropic-ai", disallow: "/" },
      { userAgent: "PerplexityBot", disallow: "/" },
      // Google-Extended (Gemini training) — selective
      {
        userAgent: "Google-Extended",
        allow: "/",
        disallow: ["/gallery/", "/api/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
